/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TheAmazingTozziDuckMachine } from "./TheAmazingTozziDuckMachine";
export * as factories from "./factories";
export { TheAmazingTozziDuckMachine__factory } from "./factories/TheAmazingTozziDuckMachine__factory";
