/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type MachineConfigStruct = {
  tozziDuckPrice: BigNumberish;
  customDuckPrice: BigNumberish;
  maxCustomDucks: BigNumberish;
  tozziDuckMintStatus: BigNumberish;
  customDuckMintStatus: BigNumberish;
};

export type MachineConfigStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  number,
  number
] & {
  tozziDuckPrice: BigNumber;
  customDuckPrice: BigNumber;
  maxCustomDucks: BigNumber;
  tozziDuckMintStatus: number;
  customDuckMintStatus: number;
};

export type DuckStanceStruct = { stance: string; timeout: BigNumberish };

export type DuckStanceStructOutput = [string, BigNumber] & {
  stance: string;
  timeout: BigNumber;
};

export type DuckProfileStruct = {
  name: string;
  description: string;
  stance: DuckStanceStruct;
  updated: BigNumberish;
};

export type DuckProfileStructOutput = [
  string,
  string,
  DuckStanceStructOutput,
  BigNumber
] & {
  name: string;
  description: string;
  stance: DuckStanceStructOutput;
  updated: BigNumber;
};

export interface TheAmazingTozziDuckMachineInterface extends utils.Interface {
  functions: {
    "BURN_WINDOW()": FunctionFragment;
    "OWNERSHIP_TOKEN_ID()": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "burnRenegadeDuck(uint256,string)": FunctionFragment;
    "customDuckHatchedTimes(uint256)": FunctionFragment;
    "duckAllowances(address)": FunctionFragment;
    "duckCreators(uint256)": FunctionFragment;
    "duckExists(bytes32)": FunctionFragment;
    "duckIdToWEBP(uint256)": FunctionFragment;
    "duckProfiles(uint256)": FunctionFragment;
    "getApproved(uint256)": FunctionFragment;
    "isApprovedForAll(address,address)": FunctionFragment;
    "machineConfig()": FunctionFragment;
    "mintCustomDuck(string)": FunctionFragment;
    "mintTozziDuck(uint256,string,bytes32[])": FunctionFragment;
    "name()": FunctionFragment;
    "ownerOf(uint256)": FunctionFragment;
    "safeTransferFrom(address,address,uint256)": FunctionFragment;
    "safeTransferFrom(address,address,uint256,bytes)": FunctionFragment;
    "setApprovalForAll(address,bool)": FunctionFragment;
    "setDuckAllowance(address,uint128,uint128)": FunctionFragment;
    "setDuckProfile(uint256,string,string,string,uint256)": FunctionFragment;
    "setMachineConfig((uint256,uint256,uint256,uint8,uint8))": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "symbol()": FunctionFragment;
    "tokenByIndex(uint256)": FunctionFragment;
    "tokenOfOwnerByIndex(address,uint256)": FunctionFragment;
    "tokenURI(uint256)": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
    "withdraw(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "BURN_WINDOW"
      | "OWNERSHIP_TOKEN_ID"
      | "approve"
      | "balanceOf"
      | "burnRenegadeDuck"
      | "customDuckHatchedTimes"
      | "duckAllowances"
      | "duckCreators"
      | "duckExists"
      | "duckIdToWEBP"
      | "duckProfiles"
      | "getApproved"
      | "isApprovedForAll"
      | "machineConfig"
      | "mintCustomDuck"
      | "mintTozziDuck"
      | "name"
      | "ownerOf"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setDuckAllowance"
      | "setDuckProfile"
      | "setMachineConfig"
      | "supportsInterface"
      | "symbol"
      | "tokenByIndex"
      | "tokenOfOwnerByIndex"
      | "tokenURI"
      | "totalSupply"
      | "transferFrom"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BURN_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OWNERSHIP_TOKEN_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "burnRenegadeDuck",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "customDuckHatchedTimes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "duckAllowances",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "duckCreators",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "duckExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "duckIdToWEBP",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "duckProfiles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "machineConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintCustomDuck",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintTozziDuck",
    values: [BigNumberish, string, BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setDuckAllowance",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDuckProfile",
    values: [BigNumberish, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMachineConfig",
    values: [MachineConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOfOwnerByIndex",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BURN_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OWNERSHIP_TOKEN_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "burnRenegadeDuck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "customDuckHatchedTimes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "duckAllowances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "duckCreators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "duckExists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "duckIdToWEBP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "duckProfiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "machineConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintCustomDuck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintTozziDuck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDuckAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDuckProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMachineConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOfOwnerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "ApprovalForAll(address,address,bool)": EventFragment;
    "CustomDuckBurned(uint256,address,address,string)": EventFragment;
    "DuckMinted(uint256,address,uint8,uint256)": EventFragment;
    "DuckProfileUpdated(uint256,address,tuple)": EventFragment;
    "MachineConfigUpdated(address,uint256,uint256,uint256,uint8,uint8)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ApprovalForAll"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CustomDuckBurned"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DuckMinted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DuckProfileUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MachineConfigUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export interface ApprovalEventObject {
  owner: string;
  approved: string;
  tokenId: BigNumber;
}
export type ApprovalEvent = TypedEvent<
  [string, string, BigNumber],
  ApprovalEventObject
>;

export type ApprovalEventFilter = TypedEventFilter<ApprovalEvent>;

export interface ApprovalForAllEventObject {
  owner: string;
  operator: string;
  approved: boolean;
}
export type ApprovalForAllEvent = TypedEvent<
  [string, string, boolean],
  ApprovalForAllEventObject
>;

export type ApprovalForAllEventFilter = TypedEventFilter<ApprovalForAllEvent>;

export interface CustomDuckBurnedEventObject {
  duckId: BigNumber;
  admin: string;
  owner: string;
  reason: string;
}
export type CustomDuckBurnedEvent = TypedEvent<
  [BigNumber, string, string, string],
  CustomDuckBurnedEventObject
>;

export type CustomDuckBurnedEventFilter =
  TypedEventFilter<CustomDuckBurnedEvent>;

export interface DuckMintedEventObject {
  tokenId: BigNumber;
  who: string;
  duckType: number;
  price: BigNumber;
}
export type DuckMintedEvent = TypedEvent<
  [BigNumber, string, number, BigNumber],
  DuckMintedEventObject
>;

export type DuckMintedEventFilter = TypedEventFilter<DuckMintedEvent>;

export interface DuckProfileUpdatedEventObject {
  duckId: BigNumber;
  updatedBy: string;
  profile: DuckProfileStructOutput;
}
export type DuckProfileUpdatedEvent = TypedEvent<
  [BigNumber, string, DuckProfileStructOutput],
  DuckProfileUpdatedEventObject
>;

export type DuckProfileUpdatedEventFilter =
  TypedEventFilter<DuckProfileUpdatedEvent>;

export interface MachineConfigUpdatedEventObject {
  who: string;
  tozziDuckPrice: BigNumber;
  customDuckPrice: BigNumber;
  maxCustomDucks: BigNumber;
  tozziDuckMintStatus: number;
  customDuckMintStatus: number;
}
export type MachineConfigUpdatedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, number, number],
  MachineConfigUpdatedEventObject
>;

export type MachineConfigUpdatedEventFilter =
  TypedEventFilter<MachineConfigUpdatedEvent>;

export interface TransferEventObject {
  from: string;
  to: string;
  tokenId: BigNumber;
}
export type TransferEvent = TypedEvent<
  [string, string, BigNumber],
  TransferEventObject
>;

export type TransferEventFilter = TypedEventFilter<TransferEvent>;

export interface TheAmazingTozziDuckMachine extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TheAmazingTozziDuckMachineInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BURN_WINDOW(overrides?: CallOverrides): Promise<[BigNumber]>;

    OWNERSHIP_TOKEN_ID(overrides?: CallOverrides): Promise<[BigNumber]>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    burnRenegadeDuck(
      duckId: BigNumberish,
      reason: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    customDuckHatchedTimes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    duckAllowances(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        tozziDuckAllowance: BigNumber;
        customDuckAllowance: BigNumber;
      }
    >;

    duckCreators(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    duckExists(arg0: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    duckIdToWEBP(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    duckProfiles(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, DuckStanceStructOutput, BigNumber] & {
        name: string;
        description: string;
        stance: DuckStanceStructOutput;
        updated: BigNumber;
      }
    >;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    machineConfig(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, number, number] & {
        tozziDuckPrice: BigNumber;
        customDuckPrice: BigNumber;
        maxCustomDucks: BigNumber;
        tozziDuckMintStatus: number;
        customDuckMintStatus: number;
      }
    >;

    mintCustomDuck(
      webp: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mintTozziDuck(
      duckId: BigNumberish,
      webp: string,
      merkleProof: BytesLike[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    name(overrides?: CallOverrides): Promise<[string]>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDuckAllowance(
      who: string,
      tozziDuckAllowance: BigNumberish,
      customDuckAllowance: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDuckProfile(
      tokenId: BigNumberish,
      _name: string,
      _description: string,
      _stance: string,
      _stanceTimeout: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMachineConfig(
      config: MachineConfigStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    tokenByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tokenOfOwnerByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  BURN_WINDOW(overrides?: CallOverrides): Promise<BigNumber>;

  OWNERSHIP_TOKEN_ID(overrides?: CallOverrides): Promise<BigNumber>;

  approve(
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

  burnRenegadeDuck(
    duckId: BigNumberish,
    reason: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  customDuckHatchedTimes(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  duckAllowances(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      tozziDuckAllowance: BigNumber;
      customDuckAllowance: BigNumber;
    }
  >;

  duckCreators(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  duckExists(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  duckIdToWEBP(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  duckProfiles(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, DuckStanceStructOutput, BigNumber] & {
      name: string;
      description: string;
      stance: DuckStanceStructOutput;
      updated: BigNumber;
    }
  >;

  getApproved(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  isApprovedForAll(
    owner: string,
    operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  machineConfig(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, number, number] & {
      tozziDuckPrice: BigNumber;
      customDuckPrice: BigNumber;
      maxCustomDucks: BigNumber;
      tozziDuckMintStatus: number;
      customDuckMintStatus: number;
    }
  >;

  mintCustomDuck(
    webp: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mintTozziDuck(
    duckId: BigNumberish,
    webp: string,
    merkleProof: BytesLike[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  name(overrides?: CallOverrides): Promise<string>;

  ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "safeTransferFrom(address,address,uint256)"(
    from: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "safeTransferFrom(address,address,uint256,bytes)"(
    from: string,
    to: string,
    tokenId: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setApprovalForAll(
    operator: string,
    approved: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDuckAllowance(
    who: string,
    tozziDuckAllowance: BigNumberish,
    customDuckAllowance: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDuckProfile(
    tokenId: BigNumberish,
    _name: string,
    _description: string,
    _stance: string,
    _stanceTimeout: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMachineConfig(
    config: MachineConfigStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  symbol(overrides?: CallOverrides): Promise<string>;

  tokenByIndex(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tokenOfOwnerByIndex(
    owner: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  transferFrom(
    from: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    BURN_WINDOW(overrides?: CallOverrides): Promise<BigNumber>;

    OWNERSHIP_TOKEN_ID(overrides?: CallOverrides): Promise<BigNumber>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    burnRenegadeDuck(
      duckId: BigNumberish,
      reason: string,
      overrides?: CallOverrides
    ): Promise<void>;

    customDuckHatchedTimes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    duckAllowances(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        tozziDuckAllowance: BigNumber;
        customDuckAllowance: BigNumber;
      }
    >;

    duckCreators(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    duckExists(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    duckIdToWEBP(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    duckProfiles(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, DuckStanceStructOutput, BigNumber] & {
        name: string;
        description: string;
        stance: DuckStanceStructOutput;
        updated: BigNumber;
      }
    >;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    machineConfig(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, number, number] & {
        tozziDuckPrice: BigNumber;
        customDuckPrice: BigNumber;
        maxCustomDucks: BigNumber;
        tozziDuckMintStatus: number;
        customDuckMintStatus: number;
      }
    >;

    mintCustomDuck(webp: string, overrides?: CallOverrides): Promise<void>;

    mintTozziDuck(
      duckId: BigNumberish,
      webp: string,
      merkleProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    name(overrides?: CallOverrides): Promise<string>;

    ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setDuckAllowance(
      who: string,
      tozziDuckAllowance: BigNumberish,
      customDuckAllowance: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setDuckProfile(
      tokenId: BigNumberish,
      _name: string,
      _description: string,
      _stance: string,
      _stanceTimeout: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMachineConfig(
      config: MachineConfigStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    symbol(overrides?: CallOverrides): Promise<string>;

    tokenByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenOfOwnerByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Approval(address,address,uint256)"(
      owner?: string | null,
      approved?: string | null,
      tokenId?: BigNumberish | null
    ): ApprovalEventFilter;
    Approval(
      owner?: string | null,
      approved?: string | null,
      tokenId?: BigNumberish | null
    ): ApprovalEventFilter;

    "ApprovalForAll(address,address,bool)"(
      owner?: string | null,
      operator?: string | null,
      approved?: null
    ): ApprovalForAllEventFilter;
    ApprovalForAll(
      owner?: string | null,
      operator?: string | null,
      approved?: null
    ): ApprovalForAllEventFilter;

    "CustomDuckBurned(uint256,address,address,string)"(
      duckId?: null,
      admin?: null,
      owner?: null,
      reason?: null
    ): CustomDuckBurnedEventFilter;
    CustomDuckBurned(
      duckId?: null,
      admin?: null,
      owner?: null,
      reason?: null
    ): CustomDuckBurnedEventFilter;

    "DuckMinted(uint256,address,uint8,uint256)"(
      tokenId?: BigNumberish | null,
      who?: string | null,
      duckType?: BigNumberish | null,
      price?: null
    ): DuckMintedEventFilter;
    DuckMinted(
      tokenId?: BigNumberish | null,
      who?: string | null,
      duckType?: BigNumberish | null,
      price?: null
    ): DuckMintedEventFilter;

    "DuckProfileUpdated(uint256,address,tuple)"(
      duckId?: null,
      updatedBy?: null,
      profile?: null
    ): DuckProfileUpdatedEventFilter;
    DuckProfileUpdated(
      duckId?: null,
      updatedBy?: null,
      profile?: null
    ): DuckProfileUpdatedEventFilter;

    "MachineConfigUpdated(address,uint256,uint256,uint256,uint8,uint8)"(
      who?: string | null,
      tozziDuckPrice?: null,
      customDuckPrice?: null,
      maxCustomDucks?: null,
      tozziDuckMintStatus?: null,
      customDuckMintStatus?: null
    ): MachineConfigUpdatedEventFilter;
    MachineConfigUpdated(
      who?: string | null,
      tozziDuckPrice?: null,
      customDuckPrice?: null,
      maxCustomDucks?: null,
      tozziDuckMintStatus?: null,
      customDuckMintStatus?: null
    ): MachineConfigUpdatedEventFilter;

    "Transfer(address,address,uint256)"(
      from?: string | null,
      to?: string | null,
      tokenId?: BigNumberish | null
    ): TransferEventFilter;
    Transfer(
      from?: string | null,
      to?: string | null,
      tokenId?: BigNumberish | null
    ): TransferEventFilter;
  };

  estimateGas: {
    BURN_WINDOW(overrides?: CallOverrides): Promise<BigNumber>;

    OWNERSHIP_TOKEN_ID(overrides?: CallOverrides): Promise<BigNumber>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    burnRenegadeDuck(
      duckId: BigNumberish,
      reason: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    customDuckHatchedTimes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    duckAllowances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    duckCreators(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    duckExists(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    duckIdToWEBP(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    duckProfiles(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    machineConfig(overrides?: CallOverrides): Promise<BigNumber>;

    mintCustomDuck(
      webp: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mintTozziDuck(
      duckId: BigNumberish,
      webp: string,
      merkleProof: BytesLike[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDuckAllowance(
      who: string,
      tozziDuckAllowance: BigNumberish,
      customDuckAllowance: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDuckProfile(
      tokenId: BigNumberish,
      _name: string,
      _description: string,
      _stance: string,
      _stanceTimeout: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMachineConfig(
      config: MachineConfigStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    tokenByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenOfOwnerByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BURN_WINDOW(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    OWNERSHIP_TOKEN_ID(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    balanceOf(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    burnRenegadeDuck(
      duckId: BigNumberish,
      reason: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    customDuckHatchedTimes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    duckAllowances(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    duckCreators(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    duckExists(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    duckIdToWEBP(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    duckProfiles(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    machineConfig(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintCustomDuck(
      webp: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mintTozziDuck(
      duckId: BigNumberish,
      webp: string,
      merkleProof: BytesLike[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDuckAllowance(
      who: string,
      tozziDuckAllowance: BigNumberish,
      customDuckAllowance: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDuckProfile(
      tokenId: BigNumberish,
      _name: string,
      _description: string,
      _stance: string,
      _stanceTimeout: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMachineConfig(
      config: MachineConfigStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenByIndex(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenOfOwnerByIndex(
      owner: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
